[package]
name = "paxsite"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["paxgen", "."]

[workspace.dependencies]
anyhow = "1.0"

[dependencies]
anyhow = { workspace = true }

paxgen = { path = "paxgen" }

[features]
default = ["serve"]
serve = ["paxgen/serve"]

[profile.dev.package]
image.opt-level = 3
crc32fast.opt-level = 3
miniz_oxide.opt-level = 3
png.opt-level = 3
