[package]
name = "paxsite"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["paxgen", "."]

[workspace.dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
image = { version = "0.25.1", features = [
    "png",
    "ico",
], default-features = false }
chrono = "0.4.37"

[dependencies]
anyhow = { workspace = true }
image = { workspace = true }
chrono = { workspace = true }

file-serve = { version = "0.3.2", optional = true }

paxgen = { path = "paxgen" }

[features]
default = ["serve"]
serve = ["dep:file-serve"]
