[package]
name = "paxsite"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "paxhtml"]

[workspace.dependencies]
anyhow = "1.0"
chrono = { version = "0.4.37", default-features = false, features = [
    "std",
    "now",
] }

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }

paxhtml = { path = "paxhtml" }

file-serve = { version = "0.3.2", optional = true }
image = { version = "0.25.1", features = [
    "png",
    "ico",
], default-features = false }
markdown = "1.0.0-alpha.16"
reqwest = { version = "0.12", default-features = false, features = [
    "blocking",
    "default-tls",
], optional = true }
rss = { version = "2.0.7", features = ["atom"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.12"
toml-datetime-compat = { version = "0.3.0", features = ["chrono"] }

[features]
default = ["serve", "fonts"]
serve = ["dep:file-serve"]
fonts = ["dep:reqwest"]

[profile.dev.package]
image.opt-level = 3
crc32fast.opt-level = 3
miniz_oxide.opt-level = 3
png.opt-level = 3
