[package]
name = "paxsite"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["paxgen", ".", "paxhtml"]

[workspace.dependencies]
anyhow = "1.0"
chrono = { version = "0.4.37", default-features = false, features = [
    "std",
    "now",
] }

[dependencies]
anyhow = { workspace = true }

paxgen = { path = "paxgen" }
paxhtml = { path = "paxhtml" }

reqwest = { version = "0.12", default-features = false, features = [
    "blocking",
    "default-tls",
], optional = true }

[features]
default = ["serve", "fonts"]
serve = ["paxgen/serve"]
fonts = ["dep:reqwest"]

[profile.dev.package]
image.opt-level = 3
crc32fast.opt-level = 3
miniz_oxide.opt-level = 3
png.opt-level = 3
