[package]
name = "paxsite"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
chrono = "0.4.37"
html-escape = "0.2.13"
image = "0.25.1"
markdown = "1.0.0-alpha.16"
rss = { version = "2.0.7", features = ["atom"] }
serde = { version = "1.0.197", features = ["derive"] }
toml = "0.8.12"
toml-datetime-compat = { version = "0.2.0", features = ["chrono"] }
