base_url = "https://philpax.me"
build_search_index = false
compile_sass = true
description = "your friendly neighbourhood polyglot programmer/engineer"
taxonomies = [
  {name = "tags"},
]
theme = "zerm"
title = "Philpax"

[markdown]
highlight_code = true

[extra]
author = "Philpax"
center = true
copyright = "© philpax"
disqus = {enabled = false, short_name = ""}
enable_katex = false
full_width = false
logo_home_link = "/"
logo_text = "philpax"
main_menu = [
  {url = "/", name = "blog"},
  {url = "https://github.com/philpax", name = "github", external = true},
  {url = "https://twitter.com/philpax_", name = "twitter", external = true},
  {url = "/about/", name = "about"},
]
menu_more = "show more"
read_more = "read more"
read_other_posts = "read other posts"
show_author = false
show_categories = true
show_menu_items = 999
show_tags = true
theme_color = "purple"
