[package]
name = "paxhtml"
version = "0.1.0"
edition = "2021"

[dependencies]
html-escape = "0.2.13"

paxhtml_macro = { path = "../paxhtml_macro", optional = true }

[features]
default = ["macros"]
macros = ["paxhtml_macro"]
